import type { Metadata } from 'next';
import RecoilRootProvider from '@/utils/recoilRootProvider';

import { Inter } from 'next/font/google';
import './global.css';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  viewport: 'width=device-width, initial-scale=1, maximum-scale=1',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={inter.className}>
        <div className="flex justify-center bg-[#d9d9d9]">
          <div className="min-h-screen w-[430px] max-w-[430px] bg-[#fff]">
            <RecoilRootProvider>{children}</RecoilRootProvider>
          </div>
        </div>
      </body>
    </html>
  );
}
